/**
 * CONFLICT MONITORING DASHBOARD TYPES
 * 
 * Feature 10: Conflict Monitoring Dashboard
 * Corresponds to:
 * - Image 1: CoScripta Dashboard UI
 * - Image 2: "8. Conflict Metrics Dashboard" (Statistics, Resolution Success Rates, Coverage Information, AI Effectiveness)
 */

export interface DashboardProject {
    id: string;
    name: string;
    description: string;
    membersCount: number;
    memberAvatars: string[];
    lastModified: string;
    status: 'Active' | 'Paused' | 'Archived';
    roomId: string;
}

export interface DashboardActivity {
    id: string;
    iconType: 'edit' | 'conflict' | 'join' | 'version' | 'comment' | 'resolved';
    text: string;
    highlightProject: string;
    timestampText: string;
    timestamp: number;
}

export interface ConflictOverviewStats {
    detected: number;          // 8
    resolved: number;          // 5
    pending: number;           // 3
    aiSuggestions: number;     // 4 (Generated by Gemini)
    validationPassed: number;  // 6 (Ready to merge)
}

export interface AIMetricsReport {
    resolutionSuccessRate: number; // 83.3%
    overallResolutionRate: number; // 62.5% (5/8)
    lineCoverageAvg: number;        // 94.6%
    branchCoverageAvg: number;      // 92.5%
    aiEffectivenessScore: number;   // 92/100
    averageResolutionTimeSeconds: number; // 24s
    regressionsPrevented: number;   // 18
    categoryBreakdown: Array<{
        category: string;
        detected: number;
        aiResolved: number;
        successRate: number;
    }>;
}

export interface FullDashboardData {
    user: {
        name: string;
        role: string;
        avatarText: string;
        greeting: string;
    };
    topStats: {
        myProjects: number;        // 4
        activeUsers: number;       // 7
        pendingConflicts: number;  // 3
        recentVersions: number;    // 12
    };
    projects: DashboardProject[];
    recentActivity: DashboardActivity[];
    conflictOverview: ConflictOverviewStats;
    aiMetrics: AIMetricsReport;
    serverStatus: {
        online: boolean;
        message: string;
        uptimeSeconds: number;
    };
}
