/**
 * CONFLICT MONITORING DASHBOARD METRICS SERVICE
 * 
 * Feature 10: Conflict Monitoring Dashboard
 * Corresponds to:
 * - Image 1: CoScripta Activity Dashboard (Projects, Users, Conflicts, Versions, Activities)
 * - Image 2: "8. Conflict Metrics Dashboard"
 *   - Displays conflict statistics, resolution success rates, and coverage information.
 *   - Helps measure how effectively the AI is resolving conflicts.
 */

export interface DashboardProject {
    id: string;
    name: string;
    description: string;
    membersCount: number;
    memberAvatars: string[];
    lastModified: string;
    status: 'Active' | 'Paused' | 'Archived';
    roomId: string;
}

export interface DashboardActivity {
    id: string;
    iconType: 'edit' | 'conflict' | 'join' | 'version' | 'comment' | 'resolved';
    text: string;
    highlightProject: string;
    timestampText: string;
    timestamp: number;
}

export interface ConflictOverviewStats {
    detected: number;          // 8
    resolved: number;          // 5
    pending: number;           // 3
    aiSuggestions: number;     // 4 (Generated by Gemini)
    validationPassed: number;  // 6 (Ready to merge)
}

export interface AIMetricsReport {
    resolutionSuccessRate: number; // 83.3%
    overallResolutionRate: number; // 62.5% (5/8)
    lineCoverageAvg: number;        // 94.6%
    branchCoverageAvg: number;      // 92.5%
    aiEffectivenessScore: number;   // 92/100
    averageResolutionTimeSeconds: number; // 24s
    regressionsPrevented: number;   // 18
    categoryBreakdown: Array<{
        category: string;
        detected: number;
        aiResolved: number;
        successRate: number;
    }>;
}

export interface FullDashboardData {
    user: {
        name: string;
        role: string;
        avatarText: string;
        greeting: string;
    };
    topStats: {
        myProjects: number;        // 4
        activeUsers: number;       // 7
        pendingConflicts: number;  // 3
        recentVersions: number;    // 12
    };
    projects: DashboardProject[];
    recentActivity: DashboardActivity[];
    conflictOverview: ConflictOverviewStats;
    aiMetrics: AIMetricsReport;
    serverStatus: {
        online: boolean;
        message: string;
        uptimeSeconds: number;
    };
}

export class DashboardMetricsService {
    public static getDashboardData(userName?: string): FullDashboardData {
        const devName = userName || "Developer";
        return {
            user: {
                name: devName,
                role: "Lead Engineer",
                avatarText: devName.charAt(0).toUpperCase() || "D",
                greeting: `Welcome back, ${devName}! 👋`
            },
            topStats: {
                myProjects: 4,
                activeUsers: 7,
                pendingConflicts: 3,
                recentVersions: 12
            },
            projects: [
                {
                    id: "codesync-core",
                    name: "CodeSync Core",
                    description: "Real-time CRDT & WebRTC collaboration engine",
                    membersCount: 4,
                    memberAvatars: ["A", "D", "K", "S"],
                    lastModified: "10 mins ago",
                    status: "Active",
                    roomId: "codesync-core"
                },
                {
                    id: "ast-semantic-engine",
                    name: "AST Semantic Engine",
                    description: "Structural AST parser & AI conflict detector",
                    membersCount: 3,
                    memberAvatars: ["E", "M", "R"],
                    lastModified: "32 mins ago",
                    status: "Active",
                    roomId: "ast-engine"
                },
                {
                    id: "docker-sandbox-suite",
                    name: "Docker Sandbox Suite",
                    description: "Isolated multi-test execution runner",
                    membersCount: 2,
                    memberAvatars: ["T", "V"],
                    lastModified: "2 hours ago",
                    status: "Active",
                    roomId: "docker-sandbox"
                },
                {
                    id: "distributed-crdt",
                    name: "Distributed CRDT",
                    description: "Centralized Redis state persistence & pub/sub",
                    membersCount: 3,
                    memberAvatars: ["N", "P", "Y"],
                    lastModified: "1 day ago",
                    status: "Active",
                    roomId: "distributed-crdt"
                }
            ],
            recentActivity: [
                {
                    id: "act-1",
                    iconType: "edit",
                    text: "Collaborator edited userService.ts in CodeSync Core",
                    highlightProject: "CodeSync Core",
                    timestampText: "10 minutes ago",
                    timestamp: Date.now() - 10 * 60 * 1000
                },
                {
                    id: "act-2",
                    iconType: "conflict",
                    text: "Semantic conflict #24 detected in calculateSalary()",
                    highlightProject: "AST Semantic Engine",
                    timestampText: "32 minutes ago",
                    timestamp: Date.now() - 32 * 60 * 1000
                },
                {
                    id: "act-3",
                    iconType: "join",
                    text: "Team member joined room 'codesync-core' via WebRTC",
                    highlightProject: "CodeSync Core",
                    timestampText: "1 hour ago",
                    timestamp: Date.now() - 60 * 60 * 1000
                },
                {
                    id: "act-4",
                    iconType: "version",
                    text: "CRDT snapshot v1.4 converged across all peers",
                    highlightProject: "Distributed CRDT",
                    timestampText: "2 hours ago",
                    timestamp: Date.now() - 2 * 60 * 60 * 1000
                },
                {
                    id: "act-5",
                    iconType: "comment",
                    text: "Review comment posted on AST type inference rules",
                    highlightProject: "AST Semantic Engine",
                    timestampText: "3 hours ago",
                    timestamp: Date.now() - 3 * 60 * 60 * 1000
                },
                {
                    id: "act-6",
                    iconType: "resolved",
                    text: "AI Suggestion applied with 94% confidence (17/17 tests passing)",
                    highlightProject: "CodeSync Core",
                    timestampText: "5 hours ago",
                    timestamp: Date.now() - 5 * 60 * 60 * 1000
                }
            ],
            conflictOverview: {
                detected: 8,
                resolved: 5,
                pending: 3,
                aiSuggestions: 4,
                validationPassed: 6
            },
            aiMetrics: {
                resolutionSuccessRate: 83.3,
                overallResolutionRate: 62.5,
                lineCoverageAvg: 94.6,
                branchCoverageAvg: 92.5,
                aiEffectivenessScore: 92,
                averageResolutionTimeSeconds: 24,
                regressionsPrevented: 18,
                categoryBreakdown: [
                    { category: "Type Mismatches", detected: 3, aiResolved: 3, successRate: 100.0 },
                    { category: "Interface Signatures", detected: 2, aiResolved: 2, successRate: 100.0 },
                    { category: "Dependency Breaks", detected: 2, aiResolved: 1, successRate: 50.0 },
                    { category: "Duplicate Declarations", detected: 1, aiResolved: 1, successRate: 100.0 }
                ]
            },
            serverStatus: {
                online: true,
                message: "All systems operational",
                uptimeSeconds: Math.floor(process.uptime())
            }
        };
    }
}
